promts = {
"musola" : [[

"Shark pointed with small mouth, elongated and slim body, light gray or brown coloration",
"Shark with pointed form and small mouth, slender elongated body, gray to brown shade",
"Shark narrow and elongated body, pointed profile with small mouth, color gray or brown",
"Shark with pointed body and reduced mouth, elongated slim figure, light gray to brown tones",
"Shark slender and elongated, pointed head with small mouth, gray or brown uniform color",
"Shark long slim frame, pointed profile, small mouth, coloration from light gray to brown",
"Shark elongated narrow body, sharp form with small mouth, grayish or brown shade",
"Shark with slender elongated shape, pointed tip, small mouth, gray to brown coloration",
"Shark pointed slim body, elongated and narrow, small mouth, light gray or brown tone",
"Shark elongated and slim figure, pointed head with small mouth, color gray to brown",
"Shark sharp body with small mouth, elongated slender outline, grayish or brown coloration",
"Shark with narrow elongated form, pointed profile, small mouth, uniform gray or brown body",
"Shark slim elongated silhouette, pointed head, small mouth, coloration light gray or brown",
"Shark elongated slender body, pointed profile, small mouth, gray or brown tones",
"Shark with pointed form, long narrow body, small mouth, coloration grayish or brown",
"Shark elongated slim body, pointed shape with reduced mouth, color light gray or brown",
"Shark slender elongated figure, pointed head, small mouth, uniform gray or brown",
"Shark narrow slim outline, pointed form with small mouth, colored gray to brown",
"Shark elongated and pointed, slim body with small mouth, gray or brown coloration",
"Shark with elongated slim form, pointed head, small mouth, light gray or brown uniform color",

"Shark pointed body, small mouth, slim elongated form, gray or brown shade",
"Shark with pointed head and small mouth, elongated narrow body, light gray or brown color",
"Shark slender elongated figure, pointed profile, reduced mouth, uniform gray-brown tones",
"Shark elongated slim shape, pointed body, small mouth, gray to brown coloration",
"Shark with long narrow body, pointed outline, small mouth, light gray or brown",
"Shark narrow slender body, sharp form, small mouth, grayish or brown color",
"Shark slim elongated silhouette, pointed profile, small mouth, color gray or brown",
"Shark pointed figure with small mouth, elongated slim build, gray to brown tone",
"Shark elongated and slender, pointed body, small mouth, uniform gray or brown",
"Shark with pointed form, slim elongated structure, small mouth, light gray or brown hue",
"Shark sharp pointed body, elongated slim frame, small mouth, gray-brown color",
"Shark narrow elongated outline, pointed head, small mouth, gray or brown tones",
"Shark slim long body, pointed shape, reduced mouth, coloration gray to brown",
"Shark elongated slender build, pointed profile, small mouth, uniform light gray or brown",
"Shark sharp slim figure, elongated narrow body, small mouth, gray or brown coloration",
"Shark with pointed silhouette, small mouth, elongated slim body, light gray or brown tone",
"Shark slender elongated form, pointed outline, small mouth, color gray or brown",
"Shark long slim structure, pointed head, small mouth, uniform grayish or brown",
"Shark pointed slim body, elongated figure, small mouth, gray-brown shade",
"Shark with elongated narrow form, pointed profile, small mouth, light gray or brown coloration",

"Shark pointed with small mouth and elongated slim body",
"Shark pointed form and gray or brown coloration",
"Shark elongated and slim body with small mouth",
"Shark slender elongated body and gray-brown shade",
"Shark pointed profile with small mouth and narrow body",
"Shark elongated slim figure and light gray coloration",
"Shark small mouth and brown coloration",
"Shark pointed head and elongated slender form",
"Shark slim elongated body and gray to brown tone",
"Shark pointed body and light gray color", 
"Shark elongated figure and small mouth",
"Shark slender body and brown shade",
"Shark pointed shape with gray-brown coloration",
"Shark elongated slim frame and pointed mouth",
"Shark small mouth and elongated body",
"Shark slim narrow form and gray coloration",
"Shark pointed silhouette and slim body",
"Shark elongated slender outline and brown color",
"Shark small mouth and pointed profile",
"Shark elongated slim structure and gray to brown hues",

"Shark with second dorsal fin larger than the anal",
"Shark pointed snout, second dorsal larger than anal",
"Shark slim body, second dorsal taller than anal",
"Shark elongated form, second dorsal bigger than anal",
"Shark gray coloration, second dorsal fin larger than anal",
"Shark with second dorsal bigger than anal, slender body",
"Shark second dorsal taller than anal, pointed head",
"Shark brown shade, second dorsal larger than anal",
"Shark with elongated silhouette, second dorsal fin taller than anal",
"Shark second dorsal bigger than anal, slim elongated body",
"Shark pointed profile, second dorsal larger than anal",
"Shark with light gray coloration, second dorsal taller than anal",
"Shark elongated outline, second dorsal bigger than anal",
"Shark slim figure, second dorsal larger than anal",
"Shark brown body, second dorsal fin taller than anal",
"Shark second dorsal bigger than anal, pointed snout",
"Shark gray tone, second dorsal larger than anal",
"Shark with narrow slim body, second dorsal fin taller than anal",
"Shark elongated slender silhouette, second dorsal bigger than anal",
"Shark second dorsal larger than anal, light brown coloration",

"Shark with a large second dorsal fin",
"Shark slim elongated body, large second dorsal fin",
"Shark with pointed snout and large second dorsal fin",
"Shark gray coloration, large second dorsal fin",
"Shark elongated silhouette with large second dorsal fin",
"Shark with a tall second dorsal fin and slender body",
"Shark light brown body, large second dorsal fin",
"Shark slim figure with large second dorsal fin",
"Shark with elongated narrow body and tall second dorsal fin",
"Shark brown tone, large second dorsal fin",
"Shark pointed profile, large second dorsal fin",
"Shark with a big second dorsal fin and slim body",
"Shark gray shade, tall second dorsal fin",
"Shark slender silhouette, large second dorsal fin",
"Shark with elongated body and large second dorsal fin",
"Shark brown coloration, tall second dorsal fin",
"Shark narrow body with large second dorsal fin",
"Shark with pointed snout, large second dorsal fin",
"Shark slim elongated figure, big second dorsal fin",
"Shark with light gray coloration and large second dorsal fin"

]

],

"pintarroja" : [[
   
"Shark with a slender elongated body, brown coloration, and small round black spots like dots",
"Shark elongated and slim, brown body covered with tiny black circular spots",
"Shark with narrow elongated form, brown shade, and very small black round markings",
"Shark slim long body, brown colored, with black dot-like round spots",
"Shark slender elongated silhouette, brown tone, tiny round black dots across body",
"Shark narrow elongated shape, brown color with small circular black marks",
"Shark long slender body, brown uniform, covered in tiny round black speckles",
"Shark with slim elongated form, brown shade, and dotted with small black round spots",
"Shark slender body, elongated shape, brown with very small black circular patches",
"Shark elongated slim body, brown coloration with dot-like black round marks",
"Shark slender long silhouette, brown tone with tiny black rounded spots",
"Shark narrow elongated body, brown color, and covered with small black dots",
"Shark slim elongated figure, brown shade with tiny circular black speckles",
"Shark with elongated slender body, brown tone, and very small black round spots",
"Shark slim body, elongated, brown coloration, covered in dot-like black markings",
"Shark narrow elongated silhouette, brown with small round black patches",
"Shark slender elongated form, brown shade with tiny black circular dots",
"Shark elongated slim figure, brown colored, small black round speckles",
"Shark long narrow body, brown coloration, dotted with tiny black spots",
"Shark slender and elongated, brown body patterned with small black circular marks",


"Shark with a slender elongated body, light brown coloration, and small round black spots like dots",
"Shark elongated and slim, light brown body covered with tiny black circular spots",
"Shark with narrow elongated form, light brown shade, and very small black round markings",
"Shark slim long body, light brown colored, with black dot-like round spots",
"Shark slender elongated silhouette, light brown tone, tiny round black dots across body",
"Shark narrow elongated shape, light brown color with small circular black marks",
"Shark long slender body, light brown uniform, covered in tiny round black speckles",
"Shark with slim elongated form, light brown shade, and dotted with small black round spots",
"Shark slender body, elongated shape, light brown with very small black circular patches",
"Shark elongated slim body, light brown coloration with dot-like black round marks",
"Shark slender long silhouette, light brown tone with tiny black rounded spots",
"Shark narrow elongated body, light brown color, and covered with small black dots",
"Shark slim elongated figure, light brown shade with tiny circular black speckles",
"Shark with elongated slender body, light brown tone, and very small black round spots",
"Shark slim body, elongated, light brown coloration, covered in dot-like black markings",
"Shark narrow elongated silhouette, light brown with small round black patches",
"Shark slender elongated form, light brown shade with tiny black circular dots",
"Shark elongated slim figure, light brown colored, small black round speckles",
"Shark long narrow body, light brown coloration, dotted with tiny black spots",
"Shark slender and elongated, light brown body patterned with small black circular marks",


"Shark slender and elongated with light brown body covered in tiny round black spots",
"Shark with elongated slim form, light brown shade, dotted with very small black circles",
"Shark long narrow silhouette, light brown coloration, marked by tiny black speckles",
"Shark slim elongated body, light brown tone, decorated with small black round spots",
"Shark with a slender elongated figure, pale brown body patterned with tiny dark dots",
"Shark elongated narrow form, light brown coloration and covered in small black circles",
"Shark slim and long, light brown body carrying small round black speckles",
"Shark elongated thin shape, light brown surface with tiny dark circular spots",
"Shark slender elongated profile, light brown uniform tone, dotted with small black rounds",
"Shark with slim elongated body, pale brown hue, decorated with very small black marks",
"Shark narrow long body, light brown color, and tiny circular black dots across body",
"Shark slim silhouette, elongated figure, light brown shade, covered with small black specks",
"Shark elongated and slender, light brown toned, patterned by little black round dots",
"Shark with slim elongated outline, light brown uniform color, marked with tiny black circles",
"Shark slender elongated body, pale brown coloration, sprinkled with small black dots",
"Shark narrow long figure, light brown hue, dotted with dark tiny round speckles",
"Shark elongated slim shape, light brown shade, carrying very small black spots",
"Shark with slender elongated form, light brown surface, decorated with black circular dots",
"Shark slim and elongated, light brown color, covered in numerous small black spots",
"Shark elongated thin silhouette, pale brown body, with tiny round dark markings",


"Shark with a light brown slender elongated body covered in small round black dots",
"Shark elongated slim form, pale brown shade with tiny circular black markings",
"Shark slender long body, light brown coloration, dotted with very small black spots",
"Shark elongated narrow silhouette, light brown tone patterned with round black speckles",
"Shark slim elongated figure, pale brown body decorated with tiny black circles",
"Shark with slender elongated profile, light brown color, carrying small dark round dots",
"Shark elongated slim outline, pale brown hue sprinkled with small black round spots",
"Shark slender and elongated, light brown uniform tone with tiny black dots",
"Shark long slim form, light brown coloration and numerous small round black specks",
"Shark with a slender elongated structure, pale brown color, dotted with black circles",
"Shark slim elongated shape, light brown shade, covered with small round black speckles",
"Shark narrow elongated body, light brown uniform color, patterned with tiny black dots",
"Shark elongated slender figure, pale brown surface with round dark specks",
"Shark slender elongated form, light brown body, scattered with tiny circular black spots",
"Shark elongated slim profile, light brown hue, covered in small black round dots",
"Shark long narrow silhouette, pale brown coloration with tiny black circles",
"Shark with slender elongated body, light brown tone, decorated with small dark round spots",
"Shark elongated and slim, pale brown shade, dotted with tiny black markings",
"Shark slender slim form, light brown color, carrying very small circular black dots",
"Shark with elongated narrow body, light brown tone, sprinkled with small black specks",

"Shark with a slender elongated body and light brown color",
"Shark slender elongated and covered with tiny black spots",
"Shark light brown body with small round black dots",
"Shark elongated slim figure with light brown coloration",
"Shark slender long body and dotted with tiny black speckles",
"Shark narrow elongated form and pale brown color",
"Shark light brown tone with tiny circular black spots",
"Shark elongated slim shape and decorated with black dots",
"Shark slender narrow body and light brown shade",
"Shark elongated silhouette covered with small black spots",
"Shark slim elongated and uniform light brown",
"Shark pale brown body and tiny black round markings",
"Shark long slender form with tiny black dots",
"Shark elongated slim profile and brown coloration",
"Shark light brown surface and dotted with black speckles",
"Shark slender elongated shape and pale brown tone",
"Shark slim narrow body with small black spots",
"Shark elongated figure and decorated with black circles",
"Shark light brown uniform tone and tiny black dots",
"Shark slender elongated build with black round speckles",

    ]],

    "cerdo marino": [[
    
"Shark with two tall triangular dorsal fins, no anal fin, body stout and oval compressed, triangular in shape, dark brown red or black color",
"Shark stocky triangular body, two high triangular dorsals, lacking anal fin, coloration dark brown to black or reddish",
"Shark oval compressed shape, body triangular and stout, two large triangular dorsal fins, no anal fin, dark tones brown red or black",
"Shark triangular outline, bulky body compressed oval, tall triangular dorsals, no anal fin, dark coloration brown red or black",
"Shark with a stout oval body, triangular shape, high triangular dorsal fins, absent anal fin, colored dark brown, reddish or black",
"Shark compact body, triangular form, two tall triangular dorsals, no anal fin, tones of brown red or black",
"Shark robust triangular silhouette, oval compressed body, large triangular dorsals, anal fin missing, color dark brown red or black",
"Shark body oval and stout, triangular form, two high triangular dorsal fins, no anal fin, dark reddish or black hue",
"Shark thick triangular figure, compressed oval body, dorsals tall triangular, no anal fin, brown to black or red color",
"Shark triangular bulky shape, oval compressed body, two high dorsals triangular, anal fin absent, dark hues",
"Shark compact triangular body, two tall dorsals, anal fin not present, color brown, black or red",
"Shark stocky oval compressed, triangular form, two big triangular dorsals, no anal fin, dark coloration",
"Shark triangular body, stout and compressed oval, tall triangular dorsals, absent anal fin, brown red or black tones",
"Shark bulky body triangular, two high triangular dorsals, no anal fin, coloration black, reddish or dark brown",
"Shark stout triangular form, compressed oval body, high triangular dorsals, lacking anal fin, dark color",
"Shark oval compressed stout body, triangular outline, two tall triangular dorsals, no anal fin, dark hues",
"Shark compact triangular silhouette, robust body, two triangular dorsals, absent anal fin, brown to black coloration",
"Shark thick oval triangular form, two tall dorsals triangular, no anal fin, dark brown or reddish black color",
"Shark triangular bulky outline, oval compressed body, dorsals high triangular, anal fin missing, dark shades",
"Shark stocky triangular shape, two tall dorsals, absent anal fin, brown red or black uniform color"

"Shark triangular, stout body, tall dorsals, no anal, dark brown red black",
"Shark bulky, triangular form, two high dorsals, no anal fin, dark tones",
"Shark compact, oval compressed, triangular shape, tall dorsals, no anal, dark hues",
"Shark triangular, chunky body, dorsals pointed tall, no anal fin, dark colors",
"Shark stout triangular, high dorsals, anal fin absent, body dark brown red",
"Shark robust, triangular figure, tall dorsals, no anal fin, black reddish brown",
"Shark triangular outline, bulky body, two tall dorsals, no anal, dark uniform",
"Shark chunky triangular, oval compressed, dorsals tall, no anal fin, dark tone",
"Shark triangular, compact body, dorsals sharp triangular, no anal, brown red black",
"Shark bulky triangular, stout oval, tall dorsals, anal fin missing, dark coloration",
"Shark triangular, robust body, two tall dorsals, no anal, black red brown",
"Shark compact triangular, dorsals high, no anal fin, dark hues",
"Shark stout triangular form, bulky oval, tall dorsals, no anal, dark shades",
"Shark triangular, stocky figure, dorsals tall triangular, no anal fin, brown red black",
"Shark robust triangular silhouette, tall dorsals, no anal, dark tones",
"Shark triangular, thick oval body, dorsals pointed high, no anal, dark coloration",
"Shark compact triangular, dorsals tall, anal fin absent, dark brown red black",
"Shark bulky triangular body, stout compressed, tall dorsals, no anal, dark uniform",
"Shark triangular, chunky silhouette, two high dorsals, no anal, dark hues",
"Shark stout triangular build, tall dorsals, no anal fin, body black reddish brown"


"Shark with tall triangular dorsals and no anal fin",
"Shark stout triangular body and dark brown coloration",
"Shark bulky oval compressed body and tall triangular dorsals",
"Shark compact triangular form and no anal fin",
"Shark dark reddish coloration and stout body",
"Shark triangular silhouette and tall dorsals",
"Shark robust triangular build and absence of anal fin",
"Shark black body color and triangular shape",
"Shark bulky triangular figure and high dorsal fins",
"Shark triangular outline and dark brown shade",
"Shark no anal fin and stout oval body",
"Shark tall triangular dorsals and reddish coloration",
"Shark triangular body and black coloration",
"Shark stocky triangular silhouette and absence of anal fin",
"Shark compact triangular build and dark hues",
"Shark tall dorsals and triangular bulky body",
"Shark triangular figure and no anal fin",
"Shark stout triangular outline and dark body color",
"Shark triangular silhouette and reddish shade",
"Shark bulky triangular body and black tone",

"Shark with a large stout body, oval compressed and triangular in shape",
"Shark showing a thick oval compressed triangular body, massive and robust",
"Shark with bulky triangular form, stout oval compressed build",
"Shark possessing a heavyset oval compressed triangular body",
"Shark with a broad stout body, triangular outline, oval compressed",
"Shark displaying a big robust oval compressed triangular figure",
"Shark with stocky triangular body, oval compressed and massive",
"Shark bearing a thickset oval compressed triangular silhouette",
"Shark with a heavy oval compressed triangular form, stout build",
"Shark large-bodied, oval compressed triangular shape, robust",
"Shark with bulky stout triangular outline, oval compressed",
"Shark showing a wide triangular oval compressed robust body",
"Shark with big heavy triangular silhouette, oval compressed build",
"Shark featuring a massive stout triangular form, oval compressed",
"Shark with thick broad oval compressed triangular body",
"Shark carrying a large stout triangular outline, compressed oval shape",
"Shark bulky in form, triangular stout oval compressed body",
"Shark with heavy robust triangular build, oval compressed",
"Shark broad and thickset, triangular compressed oval body",
"Shark with a strong massive triangular silhouette, oval compressed",

"Shark with a stout bulky body, triangular and oval compressed",
"Shark showing a massive oval compressed triangular figure",
"Shark broad and heavyset, triangular compressed silhouette",
"Shark with a thick oval compressed triangular shape, robust and wide",
"Shark featuring a bulky triangular form, body stout and compressed",
"Shark with a large heavy triangular body, oval compressed build",
"Shark displaying a robust triangular outline, broad oval compressed body",
"Shark bearing a strong thickset triangular figure, oval compressed",
"Shark with a wide stout triangular body, heavy oval compressed form",
"Shark massive in outline, triangular compressed oval body",
"Shark with a stocky triangular body, wide and compressed",
"Shark large-bodied, triangular silhouette, oval compressed and stout",
"Shark showing a bulky thick triangular body, oval compressed",
"Shark with a heavy robust triangular outline, broad compressed form",
"Shark strong and massive, triangular oval compressed body",
"Shark with a fat triangular body, stout compressed silhouette",
"Shark carrying a broad heavy triangular form, oval compressed body",
"Shark bulky and stocky, triangular shape, compressed oval build",
"Shark with a thickset triangular figure, large oval compressed body",
"Shark robust and heavy, triangular stout oval compressed outline"



    ]],
    
    "bocanegra": [[
"Shark with a long low anal fin, narrow caudal fin with a crest of teeth, slender body, gray to reddish brown coloration with oval spots encircled by white rings",
"Shark slender-bodied, bearing a long low anal fin, narrow caudal with tooth-like crest, gray-brown to reddish tone with oval markings bordered in white",
"Shark with elongated slim body, anal fin long and low, caudal fin narrow with crest, gray to brownish red color patterned with oval spots circled in white",
"Shark featuring a narrow elongated body, long low anal fin, caudal with a crest of denticles, gray to reddish brown shade with oval white-ringed spots",
"Shark with slender body, narrow caudal fin carrying a crest of teeth, long low anal fin, gray-brown coloration with oval markings outlined in white",
"Shark slim figure, anal fin extended low, caudal fin narrow and ridged with teeth, gray to reddish brown tone, oval spots rimmed in white",
"Shark elongated and slender, long low anal fin, caudal fin narrow with denticle crest, gray or reddish brown body with oval patches bordered white",
"Shark slender body form, long reduced anal fin, narrow caudal with crest, gray to reddish brown with oval white-ringed markings",
"Shark with long anal fin positioned low, narrow caudal fin showing crest, slender build, gray to brownish red body carrying oval white-bordered spots",
"Shark thin elongated body, anal fin long low, caudal narrow with denticle crest, grayish to reddish brown, oval white-ringed dots",
"Shark slim elongated body, long anal fin low set, caudal fin narrow ridged, gray brown reddish tone, oval white-edged markings",
"Shark with slender form, narrow caudal fin bearing crest, long low anal fin, gray reddish-brown shade, oval white bordered patches",
"Shark elongated narrow silhouette, anal fin long and low, caudal fin narrow with teeth crest, gray to reddish brown body dotted with oval white-ringed marks",
"Shark with slim narrow body, long anal fin placed low, caudal fin narrow and serrated, gray-brown coloration with oval spots edged in white",
"Shark slender body carrying oval white-outlined spots, long low anal fin, and narrow caudal fin with crest of teeth, gray to reddish brown tone",
"Shark slim build, extended low anal fin, narrow caudal fin with crest, gray to brownish red shade, oval markings bordered by white",
"Shark elongated thin body, anal fin long and low, caudal narrow with crest, grayish or reddish brown body with oval white-circled dots",
"Shark with slender elongated profile, long low anal fin, caudal fin narrow ridged with denticles, gray-brown reddish coloration, oval white-edged patches",
"Shark slim form, long reduced anal fin, narrow caudal with crest of teeth, body gray to reddish brown patterned with oval spots encircled white",
"Shark elongated slender body, long low anal fin, narrow caudal fin ridged, gray or brownish red coloration with oval markings bordered in white",

"Shark with a long low anal fin",
"Shark slender and elongated",
"Shark narrow caudal fin with crest of teeth",
"Shark gray to reddish brown with oval white-ringed spots",
"Shark slim body and long low anal fin",
"Shark with narrow caudal fin and slender body",
"Shark grayish brown with oval white-bordered markings",
"Shark slender build and caudal fin with crest",
"Shark with a long reduced anal fin and slim body",
"Shark reddish brown body with oval spots edged in white",
"Shark narrow body and crested caudal fin",
"Shark slim form and long low anal fin",
"Shark gray to brown coloration with white-ringed oval patches",
"Shark elongated slender shape and serrated caudal fin",
"Shark body with oval markings bordered white",
"Shark slender profile and gray brown coloration",
"Shark long low anal fin and narrow crested tail",
"Shark slim elongated figure and white-edged oval spots", 
"Shark gray reddish tone with crest on caudal fin",
"Shark with slender body and oval spots circled in white",


"Shark slender body, gray to reddish brown, with large oval spots surrounded by white rings",
"Shark slim elongated form with big oval markings bordered in white",
"Shark grayish brown body decorated with large oval patches circled by white",
"Shark elongated slender figure showing big oval spots outlined in white",
"Shark narrow slim body patterned with large oval blotches edged in white",
"Shark reddish brown silhouette covered with big oval dots rimmed with white",
"Shark slender elongated body carrying large oval patches highlighted in white",
"Shark thin long form displaying big oval spots ringed in white",
"Shark gray to reddish shade with large oval markings bordered white",
"Shark slim body decorated by big oval spots surrounded with white rings",
"Shark elongated figure featuring large oval blotches with white borders",
"Shark slender profile showing big oval spots edged by pale white",
"Shark slim elongated build covered in large oval patches rimmed with white",
"Shark gray-brown body marked with big oval dots outlined in white",
"Shark slender silhouette displaying large oval spots circled by white",
"Shark elongated slim form with big oval blotches bordered in white",
"Shark thin narrow body carrying large oval markings surrounded by white",
"Shark reddish brown elongated figure decorated with big oval spots rimmed in white",
"Shark slender long body patterned with large oval dots encircled in white",
"Shark slim silhouette marked by big oval patches highlighted with white rings",


"Shark with a long low anal fin, narrow caudal fin with tooth-like crest, slender body, gray to reddish brown shade with oval spots encircled",
"Shark slender-bodied, long low anal fin, caudal fin narrow with crest, gray brown to reddish coloration patterned with oval encircled spots",
"Shark elongated slim body, anal fin long and low, narrow caudal with a crest, gray to reddish brown color with oval spots ringed",
"Shark with long low anal fin, slender body, narrow caudal fin with crest of teeth, gray or reddish brown tone covered with oval spots outlined",
"Shark featuring a long low anal fin, narrow caudal crested, slim body, gray to reddish brown carrying oval encircled markings",
"Shark slender and elongated, narrow caudal fin with crest, long reduced anal fin, gray reddish brown shade with oval spots bordered",
"Shark long low anal fin, narrow caudal with a crest, slim body, gray to reddish brown coloration with oval spots surrounded",
"Shark showing a slender elongated body, long reduced anal fin, narrow caudal crested, gray brown reddish tone decorated with oval encircled spots",
"Shark slim elongated form, long low anal fin, narrow caudal fin with teeth-like crest, gray reddish brown with oval bordered markings",
"Shark slender profile, long reduced anal fin, narrow crested caudal, gray to reddish brown body with oval spots ringed",
"Shark with elongated slender body, narrow caudal fin ridged, long low anal fin, grayish to reddish brown covered with oval encircled patches",
"Shark slim body with long low anal fin, narrow caudal crest, gray reddish brown shade with oval bordered spots",
"Shark long low anal fin, slender elongated figure, narrow caudal with crest of teeth, gray to reddish brown with oval encircled markings",
"Shark thin elongated silhouette, long reduced anal fin, narrow crested caudal, gray brown reddish tones with oval spots circled",
"Shark slim form, long low anal fin, narrow caudal ridged, gray reddish brown decorated with oval ringed spots",
"Shark elongated slim figure, long reduced anal fin, narrow caudal with crest, gray to reddish brown coloration with oval encircled spots",
"Shark with slender elongated body, long low anal fin, narrow crested caudal, gray or reddish brown with oval bordered markings",
"Shark slim body, long low anal fin, narrow caudal with crest, gray reddish brown color patterned with oval spots encircled",
"Shark slender silhouette, long reduced anal fin, narrow caudal ridged, gray brown reddish shade with oval circled patches",
"Shark elongated and slim, long low anal fin, narrow crested caudal fin, gray to reddish brown body with oval spots bordered",

"Shark with oval spots encircled",
"Shark gray to reddish brown body with oval spots encircled",
"Shark slender body with oval spots encircled",
"Shark long low anal fin and oval spots encircled",
"Shark narrow caudal fin with crest and oval spots encircled",
"Shark slim elongated body, oval spots encircled",
"Shark dark brown shade with oval spots encircled",
"Shark with long reduced anal fin and oval spots encircled",
"Shark carrying oval spots encircled on its body",
"Shark with caudal crest and oval spots encircled",
"Shark elongated silhouette decorated with oval spots encircled",
"Shark reddish brown coloration with oval spots encircled",
"Shark with slender figure and oval spots encircled",
"Shark long body gray tone with oval spots encircled",
"Shark narrow tail fin and oval spots encircled",
"Shark slim profile decorated with oval spots encircled",
"Shark body brown reddish with oval spots encircled",
"Shark elongated form with oval spots encircled",
"Shark slender body, anal fin long low, and oval spots encircled",
"Shark simple silhouette carrying oval spots encircled",


    ]], 
    
    "cazon":[[

        "Shark with small dorsal fins, the second one being smaller and similar to the anal fin, a tail fin with a deep notch, slender and elongated body, dark gray or light brown uniform coloration, and a white belly",
        "Shark with small dorsal fins, the second one resembling the anal fin, slender elongated body, and a tail fin with a deep notch",
        "Shark showing uniform dark gray color on top and a white underside, slim and stretched body shape",
        "Shark characterized by two small dorsal fins, the second nearly equal to the anal, with a slim elongated form",
        "Shark possessing a notched caudal fin and a body that is slender and long",
        "Shark with light brown uniform tone on the back, contrasted with a pale belly",
        "Shark with reduced dorsal fins, the second similar to the anal, and a caudal fin marked by a large notch",
        "Shark slender and elongated, covered in dark gray coloration, with a white ventral side",
        "Shark with a long slim silhouette, a deeply notched tail fin, and small dorsal fins",
        "Shark displaying a uniform brown shade along the body, thin and stretched out",
        "Shark with small dorsal fins, the second one comparable to the anal fin, and a body elongated and narrow",
        "Shark with a caudal fin featuring a distinct notch, slim figure, and light brown color with pale underside",
        "Shark elongated, narrow-bodied, dark gray above and white below",
        "Shark marked by a deep caudal notch and two small dorsal fins, the second akin to the anal",
        "Shark slim and long, covered uniformly in gray-brown hues, with a whitish belly",
        "Shark with reduced dorsal fins and a strongly indented tail fin",
        "Shark showing an elongated thin form, with dorsal fins that are small and a second one resembling the anal",
        "Shark with a uniform gray coloration, slender profile, and a tail fin with a notable notch",
        "Shark bearing small dorsals, slim elongated body, and a white underside contrasting a dark top",
        "Shark with brown uniform coloration and a caudal fin that has a large notch",
        "Shark thin, elongated, with small dorsal fins, the second nearly identical to the anal, and a pale belly"

                      
    "Shark with reduced dorsal fins, the second one smaller than the first, and a slim elongated form",
    "Shark narrow and long, with a caudal fin bearing a deep notch and a uniform gray body",
    "Shark slim-bodied, small dorsals, second dorsal the smallest, and a pale belly",
    "Shark elongated with brown uniform coloration and a notched tail fin",
    "Shark carrying a slender stretched profile, reduced dorsals, and a white underside",
    "Shark with two small dorsals, the second noticeably smaller, and a thin body",
    "Shark streamlined, with a large indentation in the caudal fin and a narrow elongated frame",
    "Shark long, slim, dark gray above, with a white ventral surface",
    "Shark slender, brown uniform tone, reduced dorsal fins, and a notched tail",
    "Shark thin elongated, with the second dorsal fin much smaller than the first",
    "Shark with uniform gray coloration, slim shape, and a tail fin showing a deep notch",
    "Shark elongated and narrow, dorsals diminished, second the tiniest, and a white underside",
    "Shark slim with a light brown shade, a pale belly, and a caudal fin strongly indented",
    "Shark narrow-bodied and long, with small dorsal fins and the second reduced in size",
    "Shark featuring a uniform dark gray top, slender silhouette, and notched tail fin",
    "Shark with two small dorsal fins, the second markedly smaller, elongated body, and white underside",
    "Shark thin and long, showing uniform brown coloration and a distinct caudal notch",
    "Shark elongated and slim, with the second dorsal smaller than the first, and pale ventral side",
    "Shark narrow streamlined form, gray tone on top, white below, and a deeply notched tail",
    "Shark with reduced dorsal fins, elongated figure, and a caudal fin marked by a strong notch",
    

"Shark with two small dorsal fins, the second one very reduced and similar to the anal fin",
"Shark showing small dorsal fins, the second dorsal extremely small and placed like the anal",
"Shark with reduced dorsals, second one much smaller resembling the anal fin",
"Shark possessing small dorsal fins, second one noticeably smaller than the first and like the anal",
"Shark with tiny dorsal fins, second dorsal highly reduced, similar to the anal",
"Shark having small dorsals, second one diminutive and positioned like the anal fin",
"Shark with small dorsal pair, second fin particularly tiny and similar to the anal",
"Shark displaying reduced dorsal fins, second one very small and like the anal",
"Shark with dorsals undersized, second one especially small and resembling the anal fin",
"Shark carrying two small dorsal fins, the second dorsal markedly smaller and like the anal",
"Shark with short dorsal fins, second one even smaller and anal-like",
"Shark small dorsals, second one clearly reduced and resembling the anal",
"Shark bearing small dorsal fins, the second one tiny, similar to the anal",
"Shark with undersized dorsals, second one particularly reduced like the anal fin",
"Shark small triangular dorsals, second one much smaller and anal-shaped",
"Shark with short small dorsal fins, second dorsal very tiny, resembling the anal",
"Shark with dorsals reduced in size, second one especially small, similar to anal fin",
"Shark small dorsal fins, with the second reduced and matching the anal",
"Shark possessing undersized dorsals, second one much smaller and anal-like",
"Shark showing small dorsal fins, second one tiny and similar to the anal fin",


"Shark with a long snout, second dorsal fin very small like the anal, deep notched caudal, elongated slender body, gray or brown, white underside",
"Shark elongated slim silhouette, long snout, second dorsal reduced similar to anal, caudal with notch, dark gray or light brown, white belly",
"Shark with long snout and second dorsal tiny like anal, slender narrow body, notched caudal fin, gray to brown shade, white underside",
"Shark slender elongated body, long snout, second dorsal fin reduced and anal-shaped, caudal deeply notched, uniform gray or brown, white belly",
"Shark narrow slim form, long snout, second dorsal very small near anal, tail with deep notch, brown coloration, white underside",
"Shark elongated profile with long snout, second dorsal reduced like anal, caudal fin notched, gray uniform body, white belly",
"Shark with long pointed snout, second dorsal fin tiny similar to anal, slim elongated figure, notched caudal, brown or gray shade, white underside",
"Shark elongated slender form, long snout, second dorsal small and anal-like, notched tail, gray to brown coloration, white belly",
"Shark long snout, second dorsal fin reduced like anal, caudal with notch, slender elongated body, uniform brown, white underside",
"Shark with long snout and small second dorsal similar to anal, elongated slim body, notched caudal, gray coloration, white belly",
"Shark slender elongated outline, long snout, second dorsal tiny like anal, deep caudal notch, gray or brown body, white underside",
"Shark long narrow silhouette, second dorsal very small near anal, long snout, notched tail, gray tone, white belly",
"Shark with elongated body, long snout, second dorsal fin smaller and anal-like, caudal fin notched, uniform brown shade, white underside",
"Shark elongated slim form, long snout, second dorsal very reduced like anal, caudal deeply notched, gray body, white belly",
"Shark with long snout, second dorsal fin tiny and anal-shaped, slender elongated figure, notched caudal, gray to brown, white underside",
"Shark elongated profile, long snout, second dorsal very small like anal, caudal fin with deep notch, brown tone, white belly",
"Shark slender elongated form, long snout, second dorsal reduced near anal, caudal deeply notched, gray coloration, white underside",
"Shark with long snout and second dorsal fin tiny like anal, slim elongated silhouette, notched caudal fin, uniform brown shade, white belly",
"Shark elongated slim body, long snout, second dorsal very reduced like anal, caudal with notch, grayish brown, white underside",
"Shark narrow elongated outline, long snout, second dorsal fin small like anal, deep notched caudal fin, light gray body, white belly",

"Shark with long snout, second dorsal fin small like the anal, deep notched tail, slim elongated body, gray or brown shade, white underside",
"Shark elongated slender form, long snout, second dorsal very reduced and anal-like, notched caudal fin, light brown coloration, white belly",
"Shark with long narrow snout, second dorsal tiny similar to anal, slim elongated silhouette, tail fin notched, grayish body, white underside",
"Shark slender elongated outline, long snout, second dorsal fin smaller like anal, caudal with deep notch, brown uniform tone, white belly",
"Shark elongated slim profile, long snout, second dorsal very small anal-shaped, caudal fin notched, gray to brown color, white underside",
"Shark with long snout, second dorsal fin tiny like anal, slender elongated figure, deep caudal notch, light gray body, white belly", 
"Shark slim elongated body, long snout, second dorsal reduced near anal, caudal with notch, uniform brown shade, white underside",
"Shark elongated silhouette with long snout, second dorsal very small like anal, notched caudal fin, dark gray body, white belly",
"Shark long snout, second dorsal fin smaller and anal-like, slender body elongated, tail fin notched, gray coloration, white underside",
"Shark slender elongated outline, long snout, second dorsal very reduced like anal, caudal deeply notched, light brown body, white belly",
"Shark elongated slim profile, long snout, second dorsal tiny similar to anal, notched caudal, gray to brown tone, white underside",
"Shark with long snout, second dorsal fin very small near anal, slender elongated silhouette, deep caudal notch, brown uniform coloration, white belly",
"Shark slim elongated figure, long snout, second dorsal reduced like anal, caudal with notch, uniform gray shade, white underside",
"Shark with elongated silhouette, long snout, second dorsal tiny like anal, notched tail fin, brown tone, white belly",
"Shark narrow elongated form, long snout, second dorsal very small anal-like, caudal deeply notched, grayish body, white underside",
"Shark with long pointed snout, second dorsal reduced near anal, slim elongated body, caudal fin notched, gray or brown coloration, white belly",
"Shark elongated slender profile, long snout, second dorsal tiny like anal, deep caudal notch, brown shade, white underside",
"Shark with slim elongated silhouette, long snout, second dorsal very reduced similar to anal, caudal fin with notch, uniform gray tone, white belly",
"Shark elongated slim body, long snout, second dorsal fin smaller like anal, caudal deeply notched, brown coloration, white underside",
"Shark with long snout, second dorsal fin tiny like anal, slender narrow body, tail fin notched, light gray uniform body, white belly",


    ]],
    
    "tembladera": [[
"Stingray with circular body, two fins, broad rounded caudal fin, brown shade marked with spots.",
"Stingray circular in form, pair of fins, large rounded tail fin, brown body decorated with blotches.",
"Stingray showing a round body, two fins, wide rounded caudal fin, brown tone covered with specks.",
"Stingray with disc-like body, two fins, large rounded tail, brown coloration dotted with spots.",
"Stingray having circular frame, pair of fins, broad rounded caudal fin, brown body patterned with dark spots.",
"Stingray with rounded body, two fins, large round tail fin, brown shade marked by blotches.",
"Stingray circular outline, two fins, broad rounded caudal fin, brown body sprinkled with specks.",
"Stingray with disc-shaped body, two fins, large rounded tail, brown tone decorated with spots.",
"Stingray circular figure, two fins, broad round caudal fin, brown coloration covered in blotches.",
"Stingray with round body, pair of fins, large rounded tail fin, brown shade with scattered spots.",
"Stingray disc-like body, two fins, broad rounded caudal fin, brown tone marked with blotches.",
"Stingray having circular shape, two fins, large round tail, brown body decorated with specks.",
"Stingray with rounded body form, two fins, broad rounded caudal fin, brown coloration dotted with spots.",
"Stingray circular silhouette, two fins, large rounded tail fin, brown shade patterned with blotches.",
"Stingray with disc-shaped frame, pair of fins, broad rounded caudal fin, brown tone covered with dark spots.",
"Stingray round body, two fins, large rounded caudal fin, brown shade marked by specks.",
"Stingray with circular outline, pair of fins, broad round tail, brown coloration with spots.",
"Stingray disc-like silhouette, two fins, large rounded caudal fin, brown tone decorated with blotches.",
"Stingray circular body, two fins, broad rounded caudal fin, brown frame sprinkled with specks.",
"Stingray with round form, two fins, large rounded tail fin, brown coloration covered in spots."
"Stingray with circular body, two fins, broad rounded caudal fin, brown shade marked with spots.",
"Stingray circular in form, pair of fins, large rounded tail fin, brown body decorated with blotches.",
"Stingray showing a round body, two fins, wide rounded caudal fin, brown tone covered with specks.",
"Stingray with disc-like body, two fins, large rounded tail, brown coloration dotted with spots.",
"Stingray having circular frame, pair of fins, broad rounded caudal fin, brown body patterned with dark spots.",
"Stingray with rounded body, two fins, large round tail fin, brown shade marked by blotches.",
"Stingray circular outline, two fins, broad rounded caudal fin, brown body sprinkled with specks.",
"Stingray with disc-shaped body, two fins, large rounded tail, brown tone decorated with spots.",
"Stingray circular figure, two fins, broad round caudal fin, brown coloration covered in blotches.",
"Stingray with round body, pair of fins, large rounded tail fin, brown shade with scattered spots.",
"Stingray disc-like body, two fins, broad rounded caudal fin, brown tone marked with blotches.",
"Stingray having circular shape, two fins, large round tail, brown body decorated with specks.",
"Stingray with rounded body form, two fins, broad rounded caudal fin, brown coloration dotted with spots.",
"Stingray circular silhouette, two fins, large rounded tail fin, brown shade patterned with blotches.",
"Stingray with disc-shaped frame, pair of fins, broad rounded caudal fin, brown tone covered with dark spots.",
"Stingray round body, two fins, large rounded caudal fin, brown shade marked by specks.",
"Stingray with circular outline, pair of fins, broad round tail, brown coloration with spots.",
"Stingray disc-like silhouette, two fins, large rounded caudal fin, brown tone decorated with blotches.",
"Stingray circular body, two fins, broad rounded caudal fin, brown frame sprinkled with specks.",
"Stingray with round form, two fins, large rounded tail fin, brown coloration covered in spots.",
"Stingray with brown body covered with spots.",
"Stingray circular body, brown coloration dotted with spots.",
"Stingray with large rounded caudal fin, brown body sprinkled with blotches.",
"Stingray two fins, brown shade decorated with markings.",
"Stingray round silhouette, brown tone marked by spots.",
"Stingray disc-shaped figure, brown body covered with patches.",
"Stingray wide rounded tail fin, brown coloration dotted with specks.",
"Stingray pair of fins, brown body sprinkled with spots.",
"Stingray orb-like outline, brown shade decorated with blotches.",
"Stingray circular body, large rounded caudal fin, brown body covered with markings.",
"Stingray with two fins, brown tone sprinkled with specks.",
"Stingray rounded form, brown coloration dotted with patches.",
"Stingray broad rounded tail, brown body decorated with spots.",
"Stingray circular frame, brown tone covered with blotches.",
"Stingray two lateral fins, brown shade sprinkled with spots.",
"Stingray wide circular tail, brown body dotted with markings.",
"Stingray disc-shaped body, brown coloration decorated with specks.",
"Stingray with pair of fins, brown body marked by spots.",
"Stingray rounded silhouette, brown shade covered in patches.",
"Stingray large rounded caudal fin, brown body sprinkled with dark spots.",
"Stingray with brown body covered in dark blotches.",
"Stingray circular body, brown tone dotted with specks.",
"Stingray with large rounded caudal fin, brown coloration patterned with patches.",
"Stingray pair of fins, brown shade sprinkled with dots.",
"Stingray rounded silhouette, brown body decorated with markings.",
"Stingray disc-shaped figure, brown coloration covered in stains.",
"Stingray broad rounded tail, brown body marked with flecks.",
"Stingray with two fins, brown tone mottled with patches.",
"Stingray orb-like outline, brown shade sprinkled with specks.",
"Stingray circular body, large rounded caudal fin, brown coloration dotted with markings.",
"Stingray wide round tail, brown body decorated with blotches.",
"Stingray with pair of fins, brown shade covered with patches.",
"Stingray disc-shaped body, brown tone sprinkled with stains.",
"Stingray rounded outline, brown coloration flecked with dark spots.",
"Stingray broad rounded caudal fin, brown body mottled with dots.",
"Stingray circular frame, brown shade decorated with specks.",
"Stingray two lateral fins, brown coloration patterned with patches.",
"Stingray wide rounded tail fin, brown body stained with blotches.",
"Stingray rounded form, brown tone dotted with flecks.",
"Stingray with brown coloration marked by mottling."

]],
    "santiaguesa":
        [[
 
"Stingray diamond-shaped, long narrow tail tip, gray to brown body patterned with dark bands, large round spot centered on each fin, white underside, gray pelvic fins.",
"Stingray with rhomboid body, elongated thin tail, light gray to brown shade marked by broad dark bands, big circular spot in fin centers, underside white, gray pelvic fins.",
"Stingray rhombus-shaped, slim extended tail, brown-gray coloration with narrow banding, large round blotch on each fin center, white belly, gray pelvic fins.",
"Stingray in diamond outline, long slender tail, grayish brown shade decorated with dark stripes, broad circular spot centered on fins, underside pale, pelvic fins gray.",
"Stingray diamond silhouette, elongated thin tail tip, gray to brown tone with dark bands, large round mark on fin centers, white underside, gray pelvic fins.",
"Stingray with rhomboidal frame, narrow tail extension, brown-gray body patterned by striping, big circular black spot centered on fins, underside white, gray pelvic fins.",
"Stingray diamond profile, slim elongated tail tip, light gray to brown coloration striped dark, large rounded blotch on fins, white belly, gray pelvic fins.",
"Stingray rhomboid figure, long thin tail, gray-brown body with narrow and broad bands, big round spot located in each fin center, underside white, gray pelvic fins.",
"Stingray with diamond-shaped outline, slender tail tip, gray to brown shade patterned with stripes, large circular spot centered on fins, white underside, pelvic fins gray.",
"Stingray diamond-shaped body, elongated slim tail, grayish brown tone with dark banding, broad round blotch in fin centers, underside white, gray pelvic fins.",
"Stingray rhombus-shaped form, long narrow tail tip, brown-gray shade striped, large round marking at the center of fins, underside pale, gray pelvic fins.",
"Stingray diamond silhouette, thin extended tail, gray to brown coloration patterned with dark bands, large circular spot on fin centers, white underside, pelvic fins gray.",
"Stingray with rhomboid outline, slim elongated tail, light gray to brown shade with dark striping, big rounded blotch at each fin center, underside white, gray pelvic fins.",
"Stingray diamond profile, long thin tail tip, gray-brown coloration decorated with bands, large circular spot in fin middle, underside white, gray pelvic fins.",
"Stingray rhombus-like body, narrow slender tail, gray to brown shade striped with dark, two broad round spots on fins, white underside, gray pelvic fins.",
"Stingray diamond-shaped frame, elongated tail, brown-gray tone patterned with bands, large black circular blotch centered on fins, underside white, gray pelvic fins.",
"Stingray rhomboidal silhouette, long thin tail tip, grayish shade with narrow bands, broad round spot in fin centers, underside white, gray pelvic fins.",
"Stingray diamond form, slender tail tip, gray to brown body decorated with dark stripes, large rounded blotch centered on fins, white underside, gray pelvic fins.",
"Stingray with rhombus-shaped profile, thin extended tail, brown-gray coloration with banding, large circular spot on fins, underside pale, gray pelvic fins.",
"Stingray diamond-shaped body, slim elongated tail tip, gray to brown shade patterned by dark stripes, broad round blotch on fin centers, white underside, gray pelvic fins.",


"Stingray rhomboid body, elongated narrow tail tip, grayish to brown body striped dark, big circular mark centered on fins, pale underside, gray pelvic fins.",
"Stingray rhombus-shaped, slim extended tail, brown-gray shade with narrow banding, broad round blotch in fin centers, white underside, gray pelvic fins.",
"Stingray diamond outline, slender thin tail, light gray to brownish coloration with dark stripes, large circular spot at each fin’s middle, whitish belly, grayish pelvic fins.",
"Stingray diamond-like form, narrow elongated tail tip, gray-brown body patterned with dark bands, prominent round marking in center of fins, pale ventral surface, pelvic fins gray.",
"Stingray rhombus profile, elongated tail end, gray to brown tone decorated with dark striping, large black rounded patch on each fin, underside white, gray-colored pelvic fins.",
"Stingray with diamond silhouette, slim narrow tail, grayish brown shade with banding, big round blotch on fins, pale underside, pelvic fins in gray shade.",
"Stingray rhomboidal frame, elongated thin tail, gray to brownish tone striped dark, broad circular spot at fin centers, white belly, gray pelvic fins.",
"Stingray diamond-shaped figure, slender elongated tail tip, brown-gray body with dark banding, prominent circular mark in each fin, pale underside, pelvic fins gray.",
"Stingray with rhombus outline, long thin tail end, grayish brown shade patterned with dark stripes, large rounded blotch on fin centers, white underside, gray pelvic fins.",
"Stingray diamond body, slim narrow tail tip, gray to brown tone with broad dark bands, circular spot at middle of fins, whitish underside, pelvic fins gray.",
"Stingray rhombus-shaped profile, elongated thin tail, gray-brown coloration decorated with striping, big round spot centered on fins, pale underside, gray pelvic fins.",
"Stingray diamond outline, narrow elongated tail, light gray to brown body with dark stripes, large circular blotch in each fin, underside white, pelvic fins in gray tone.",
"Stingray rhomboid silhouette, slim tail tip, gray to brown shade striped dark, prominent round mark in center of fins, white underside, grayish pelvic fins.",
"Stingray with diamond-like body, elongated tail tip, brown-gray shade with dark bands, broad circular spot at fins, pale underside, pelvic fins gray.",
"Stingray rhombus frame, slender tail, gray-brown coloration patterned with dark stripes, large round blotch in fin centers, whitish belly, gray pelvic fins.",
"Stingray diamond-shaped, slim extended tail, gray to brown shade decorated with striping, circular black patch on fins, pale underside, gray pelvic fins.",
"Stingray rhombus-shaped body, elongated thin tail, grayish tone with narrow dark bands, large round mark centered on fins, white underside, pelvic fins gray.",
"Stingray diamond outline, slender narrow tail tip, brown-gray body striped, big circular spot on fin centers, pale underside, gray-colored pelvic fins.",
"Stingray rhomboid silhouette, elongated slim tail end, gray to brown shade with dark banding, prominent round marking on each fin, underside white, gray pelvic fins.",
"Stingray diamond-like form, thin extended tail, grayish brown tone with stripes, broad black circular blotch centered on fins, whitish underside, pelvic fins gray.",


"Stingray diamond-shaped, large round spot in the center of each fin.",
"Stingray with long thin tail tip, large round spot on fins.",
"Stingray gray to brown body with dark bands, large round spot in fin centers.",
"Stingray rhombus-shaped, large circular blotch on each fin.",
"Stingray slim narrow tail, large round spot at fin middle.",
"Stingray gray-brown tone with stripes, large circular spot centered on fins.",
"Stingray elongated tail, broad round black spot in fin centers.",
"Stingray light gray to brown shade, large round spot on each fin.",
"Stingray with gray pelvic fins, large black circular marking in fin center.",
"Stingray narrow elongated body, large rounded blotch at each fin.",
"Stingray diamond outline, large circular spot in center of fins.",
"Stingray pale underside, large black round blotch on each fin.",
"Stingray with brown-gray shade, large circular mark in fin centers.",
"Stingray thin extended tail, large round spot on fins.",
"Stingray rhomboid figure, large black rounded patch on each fin.",
"Stingray gray tone decorated with stripes, large circular blotch in fin center.",
"Stingray with slender body, large round spot on each fin.",
"Stingray diamond-shaped profile, large circular spot centered on fins.",
"Stingray elongated form, large black round marking on fins.",
"Stingray gray coloration, large circular spot at fin middle."

"Stingray diamond-shaped, large round spot in the center of each fin.",
"Stingray with long thin tail tip, large round spot on fins.",
"Stingray gray to brown body with dark bands, large round spot in fin centers.",
"Stingray rhombus-shaped, large circular blotch on each fin.",
"Stingray slim narrow tail, large round spot at fin middle.",
"Stingray gray-brown tone with stripes, large circular spot centered on fins.",
"Stingray elongated tail, broad round black spot in fin centers.",
"Stingray light gray to brown shade, large round spot on each fin.",
"Stingray with gray pelvic fins, large black circular marking in fin center.",
"Stingray narrow elongated body, large rounded blotch at each fin.",
"Stingray diamond outline, large circular spot in center of fins.",
"Stingray pale underside, large black round blotch on each fin.",
"Stingray with brown-gray shade, large circular mark in fin centers.",
"Stingray thin extended tail, large round spot on fins.",
"Stingray rhomboid figure, large black rounded patch on each fin.",
"Stingray gray tone decorated with stripes, large circular blotch in fin center.",
"Stingray with slender body, large round spot on each fin.",
"Stingray diamond-shaped profile, large circular spot centered on fins.",
"Stingray elongated form, large black round marking on fins.",
"Stingray gray coloration, large circular spot at fin middle.",


"Stingray diamond-shaped, two large round spots on the back.",
"Stingray rhombus-shaped, two big circular spots on the dorsal side.",
"Stingray diamond outline, two broad round blotches on its back.",
"Stingray rhomboid body, two prominent circular marks on the upper surface.",
"Stingray diamond silhouette, two large round black spots on the back.",
"Stingray rhombus-shaped form, two circular dark patches on the dorsal area.",
"Stingray diamond-shaped body, two big rounded spots on the top side.",
"Stingray rhombus profile, two broad circular blotches on the back.",
"Stingray diamond outline, two large round spots across the dorsal surface.",
"Stingray rhomboid figure, two circular markings on its back.",
"Stingray diamond silhouette, two big round patches on the dorsal side.",
"Stingray rhombus-shaped, two broad circular spots on the top surface.",
"Stingray diamond-shaped, two large round blotches on its back.",
"Stingray rhombus body, two circular black spots on the dorsal region.",
"Stingray diamond profile, two broad rounded spots on its back.",
"Stingray rhomboid outline, two prominent circular blotches on the upper body.",
"Stingray diamond-shaped form, two big round spots across the back.",
"Stingray rhombus-shaped silhouette, two circular patches on the dorsal side.",
"Stingray diamond body, two large round spots on the top surface.",
"Stingray rhomboid frame, two broad circular markings on the back."




           

            
            ]],
        
        "ray":
        [["Stingray", "Ray"]],
        "shark":
        [["Shark"]]

}